# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.setEnabled(True)
        DashboardWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DashboardWindow.sizePolicy().hasHeightForWidth())
        DashboardWindow.setSizePolicy(sizePolicy)
        DashboardWindow.setMinimumSize(QtCore.QSize(1000, 800))
        DashboardWindow.setMaximumSize(QtCore.QSize(1000, 800))
        DashboardWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(DashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(380, 70, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.inventoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.inventoryButton.setGeometry(QtCore.QRect(540, 290, 381, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventoryButton.sizePolicy().hasHeightForWidth())
        self.inventoryButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.inventoryButton.setFont(font)
        self.inventoryButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inventoryButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/inventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inventoryButton.setIcon(icon)
        self.inventoryButton.setIconSize(QtCore.QSize(150, 150))
        self.inventoryButton.setObjectName("inventoryButton")
        self.receiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.receiveButton.setGeometry(QtCore.QRect(540, 500, 381, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveButton.sizePolicy().hasHeightForWidth())
        self.receiveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.receiveButton.setFont(font)
        self.receiveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.receiveButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/receive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.receiveButton.setIcon(icon1)
        self.receiveButton.setIconSize(QtCore.QSize(150, 150))
        self.receiveButton.setObjectName("receiveButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(90, 290, 381, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/addbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon2)
        self.addButton.setIconSize(QtCore.QSize(150, 150))
        self.addButton.setObjectName("addButton")
        self.sellButton = QtWidgets.QPushButton(self.centralwidget)
        self.sellButton.setGeometry(QtCore.QRect(90, 500, 381, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sellButton.sizePolicy().hasHeightForWidth())
        self.sellButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.sellButton.setFont(font)
        self.sellButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sellButton.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/sell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sellButton.setIcon(icon3)
        self.sellButton.setIconSize(QtCore.QSize(170, 170))
        self.sellButton.setObjectName("sellButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_3.setObjectName("label_3")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(850, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/logoutbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon4)
        self.logout.setIconSize(QtCore.QSize(30, 30))
        self.logout.setObjectName("logout")
        self.role = QtWidgets.QLabel(self.centralwidget)
        self.role.setGeometry(QtCore.QRect(60, 150, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.role.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.role.setFont(font)
        self.role.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.role.setObjectName("role")
        self.uid = QtWidgets.QLabel(self.centralwidget)
        self.uid.setGeometry(QtCore.QRect(60, 190, 311, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.uid.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uid.setFont(font)
        self.uid.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.uid.setObjectName("uid")
        DashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuCounterChain = QtWidgets.QMenu(self.menubar)
        self.menuCounterChain.setObjectName("menuCounterChain")
        DashboardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardWindow)
        self.statusbar.setObjectName("statusbar")
        DashboardWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(DashboardWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuCounterChain.addAction(self.actionExit)
        self.menubar.addAction(self.menuCounterChain.menuAction())

        self.retranslateUi(DashboardWindow)
        self.actionExit.triggered.connect(DashboardWindow.close)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow.setWindowTitle(_translate("DashboardWindow", "CounterChain - Dashboard"))
        self.label.setText(_translate("DashboardWindow", "Dashboard"))
        self.inventoryButton.setText(_translate("DashboardWindow", "Inventory"))
        self.receiveButton.setText(_translate("DashboardWindow", "Receive"))
        self.addButton.setText(_translate("DashboardWindow", "Add New Items"))
        self.sellButton.setText(_translate("DashboardWindow", "  Sell"))
        self.label_3.setText(_translate("DashboardWindow", "CounterChain"))
        self.logout.setText(_translate("DashboardWindow", " Log Out"))
        self.role.setText(_translate("DashboardWindow", "Role: Manufacturer"))
        self.uid.setText(_translate("DashboardWindow", "User ID"))
        self.menuCounterChain.setTitle(_translate("DashboardWindow", "CounterChain"))
        self.actionExit.setText(_translate("DashboardWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardWindow = QtWidgets.QMainWindow()
    ui = Ui_DashboardWindow()
    ui.setupUi(DashboardWindow)
    DashboardWindow.show()
    sys.exit(app.exec_())
