# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboardother.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashboardWindow_other(object):
    def setupUi(self, DashboardWindow_other):
        DashboardWindow_other.setObjectName("DashboardWindow_other")
        DashboardWindow_other.setEnabled(True)
        DashboardWindow_other.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DashboardWindow_other.sizePolicy().hasHeightForWidth())
        DashboardWindow_other.setSizePolicy(sizePolicy)
        DashboardWindow_other.setMinimumSize(QtCore.QSize(1000, 800))
        DashboardWindow_other.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(DashboardWindow_other)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(380, 70, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.inventoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.inventoryButton.setGeometry(QtCore.QRect(200, 340, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventoryButton.sizePolicy().hasHeightForWidth())
        self.inventoryButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.inventoryButton.setFont(font)
        self.inventoryButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inventoryButton.setObjectName("inventoryButton")
        self.receiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.receiveButton.setGeometry(QtCore.QRect(200, 520, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveButton.sizePolicy().hasHeightForWidth())
        self.receiveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.receiveButton.setFont(font)
        self.receiveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.receiveButton.setObjectName("receiveButton")
        self.sellButton = QtWidgets.QPushButton(self.centralwidget)
        self.sellButton.setGeometry(QtCore.QRect(200, 430, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sellButton.sizePolicy().hasHeightForWidth())
        self.sellButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.sellButton.setFont(font)
        self.sellButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sellButton.setObjectName("sellButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_3.setObjectName("label_3")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(860, 20, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logout.setFont(font)
        self.logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout.setObjectName("logout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 340, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 430, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 520, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.role = QtWidgets.QLabel(self.centralwidget)
        self.role.setGeometry(QtCore.QRect(60, 180, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.role.setFont(font)
        self.role.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.role.setObjectName("role")
        self.uid = QtWidgets.QLabel(self.centralwidget)
        self.uid.setGeometry(QtCore.QRect(60, 220, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uid.setFont(font)
        self.uid.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.uid.setObjectName("uid")
        DashboardWindow_other.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow_other)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuCounterChain = QtWidgets.QMenu(self.menubar)
        self.menuCounterChain.setObjectName("menuCounterChain")
        DashboardWindow_other.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DashboardWindow_other)
        self.statusbar.setObjectName("statusbar")
        DashboardWindow_other.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(DashboardWindow_other)
        self.actionExit.setObjectName("actionExit")
        self.menuCounterChain.addAction(self.actionExit)
        self.menubar.addAction(self.menuCounterChain.menuAction())

        self.retranslateUi(DashboardWindow_other)
        self.actionExit.triggered.connect(DashboardWindow_other.close)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow_other)

    def retranslateUi(self, DashboardWindow_other):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow_other.setWindowTitle(_translate("DashboardWindow_other", "CounterChain - Dashboard"))
        self.label.setText(_translate("DashboardWindow_other", "Dashboard"))
        self.inventoryButton.setText(_translate("DashboardWindow_other", "Inventory"))
        self.receiveButton.setText(_translate("DashboardWindow_other", "Receive"))
        self.sellButton.setText(_translate("DashboardWindow_other", "Sell"))
        self.label_3.setText(_translate("DashboardWindow_other", "CounterChain"))
        self.logout.setText(_translate("DashboardWindow_other", "Log Out"))
        self.label_4.setText(_translate("DashboardWindow_other", ">"))
        self.label_5.setText(_translate("DashboardWindow_other", ">"))
        self.label_6.setText(_translate("DashboardWindow_other", ">"))
        self.role.setText(_translate("DashboardWindow_other", "Role: Distributer/Retailer"))
        self.uid.setText(_translate("DashboardWindow_other", "User ID"))
        self.menuCounterChain.setTitle(_translate("DashboardWindow_other", "CounterChain"))
        self.actionExit.setText(_translate("DashboardWindow_other", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardWindow_other = QtWidgets.QMainWindow()
    ui = Ui_DashboardWindow_other()
    ui.setupUi(DashboardWindow_other)
    DashboardWindow_other.show()
    sys.exit(app.exec_())
