# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerWindow(object):
    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(800, 600)
        registerWindow.setMinimumSize(QtCore.QSize(800, 600))
        registerWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(registerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 751, 441))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 60, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(570, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.role = QtWidgets.QComboBox(self.tab)
        self.role.setGeometry(QtCore.QRect(532, 90, 171, 31))
        self.role.setObjectName("role")
        self.role.addItem("")
        self.role.addItem("")
        self.role.addItem("")
        self.confirm_check = QtWidgets.QCheckBox(self.tab)
        self.confirm_check.setGeometry(QtCore.QRect(50, 360, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm_check.setFont(font)
        self.confirm_check.setObjectName("confirm_check")
        self.email_LE = QtWidgets.QLineEdit(self.tab)
        self.email_LE.setGeometry(QtCore.QRect(190, 60, 230, 30))
        self.email_LE.setObjectName("email_LE")
        self.paswd_LE = QtWidgets.QLineEdit(self.tab)
        self.paswd_LE.setGeometry(QtCore.QRect(190, 130, 230, 30))
        self.paswd_LE.setObjectName("paswd_LE")
        self.name_LE = QtWidgets.QLineEdit(self.tab)
        self.name_LE.setGeometry(QtCore.QRect(190, 200, 230, 30))
        self.name_LE.setObjectName("name_LE")
        self.phone_LE = QtWidgets.QLineEdit(self.tab)
        self.phone_LE.setGeometry(QtCore.QRect(190, 280, 230, 30))
        self.phone_LE.setObjectName("phone_LE")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 211, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(50, 90, 111, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(50, 150, 191, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(50, 210, 161, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 270, 141, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(50, 330, 191, 31))
        self.label_11.setObjectName("label_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 380, 271, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(680, 10, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(355, 490, 90, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitButton.setObjectName("submitButton")
        registerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        registerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registerWindow)
        self.statusbar.setObjectName("statusbar")
        registerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(registerWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)

    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "Register"))
        self.label.setText(_translate("registerWindow", "Business E-mail:"))
        self.label_2.setText(_translate("registerWindow", "Password:"))
        self.label_3.setText(_translate("registerWindow", "Organization name:"))
        self.label_4.setText(_translate("registerWindow", "Phone no.:"))
        self.label_5.setText(_translate("registerWindow", "Select Role"))
        self.role.setItemText(0, _translate("registerWindow", "Manufacturer"))
        self.role.setItemText(1, _translate("registerWindow", "Distributer"))
        self.role.setItemText(2, _translate("registerWindow", "Retailer"))
        self.confirm_check.setText(_translate("registerWindow", "I confirm all the details are correct"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("registerWindow", "Personal Information"))
        self.label_6.setText(_translate("registerWindow", "Shops and Establishment License:"))
        self.label_7.setText(_translate("registerWindow", "Trade License:"))
        self.label_8.setText(_translate("registerWindow", "Drugs and Cosmetics License:"))
        self.label_9.setText(_translate("registerWindow", "Manufacturing License:"))
        self.label_10.setText(_translate("registerWindow", "GST Registration no.:"))
        self.label_11.setText(_translate("registerWindow", "Professional Tax Registration:"))
        self.checkBox_2.setText(_translate("registerWindow", "I confirmed all the documents are correct"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("registerWindow", "Document Verification"))
        self.backButton.setText(_translate("registerWindow", "Back"))
        self.submitButton.setText(_translate("registerWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerWindow = QtWidgets.QMainWindow()
    ui = Ui_registerWindow()
    ui.setupUi(registerWindow)
    registerWindow.show()
    sys.exit(app.exec_())
