# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receiveWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiveWindow(object):
    def setupUi(self, ReceiveWindow):
        ReceiveWindow.setObjectName("ReceiveWindow")
        ReceiveWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReceiveWindow.sizePolicy().hasHeightForWidth())
        ReceiveWindow.setSizePolicy(sizePolicy)
        ReceiveWindow.setMinimumSize(QtCore.QSize(1000, 800))
        ReceiveWindow.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(ReceiveWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 150, 251, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 260, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 250, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.rcvNextButton = QtWidgets.QPushButton(self.centralwidget)
        self.rcvNextButton.setGeometry(QtCore.QRect(410, 680, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rcvNextButton.setFont(font)
        self.rcvNextButton.setObjectName("rcvNextButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 320, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 320, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_4.setObjectName("label_4")
        self.itemList = QtWidgets.QTextBrowser(self.centralwidget)
        self.itemList.setGeometry(QtCore.QRect(260, 370, 431, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.itemList.setFont(font)
        self.itemList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.itemList.setObjectName("itemList")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(860, 20, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.homeButton.setFont(font)
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setObjectName("homeButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 0, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_5.setObjectName("label_5")
        ReceiveWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReceiveWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        ReceiveWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReceiveWindow)
        self.statusbar.setObjectName("statusbar")
        ReceiveWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReceiveWindow)
        QtCore.QMetaObject.connectSlotsByName(ReceiveWindow)

    def retranslateUi(self, ReceiveWindow):
        _translate = QtCore.QCoreApplication.translate
        ReceiveWindow.setWindowTitle(_translate("ReceiveWindow", "CounterChain - Receive Items"))
        self.label.setText(_translate("ReceiveWindow", "Receive Items"))
        self.label_2.setText(_translate("ReceiveWindow", "Seller ID:"))
        self.rcvNextButton.setText(_translate("ReceiveWindow", "Confirm"))
        self.label_3.setText(_translate("ReceiveWindow", "Product Info"))
        self.label_4.setText(_translate("ReceiveWindow", "Status"))
        self.homeButton.setText(_translate("ReceiveWindow", "Back"))
        self.label_5.setText(_translate("ReceiveWindow", "CounterChain"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiveWindow = QtWidgets.QMainWindow()
    ui = Ui_ReceiveWindow()
    ui.setupUi(ReceiveWindow)
    ReceiveWindow.show()
    sys.exit(app.exec_())
